### ISSUE TITLE
start.android not working

### ISSUE THREAD

**Issue by caraclarke** [shripalsoni04/nativescript-angular-web-starter#1]
I installed the project and have added two components to the `nativescript` folder and `app.module` in the same folder but now when I try to do `npm run start.android` I get this error

`/home/cara/Documents/proj/nativescript/app/app.android.scss SASS CSS pre-processing failed. Error: Error: File to import not found or unreadable: nativescript-theme-core/theme-core-scss/variables
Parent style sheet: /home/cara/Documents/proj/nativescript/app/scss/_variables.scss`

I ran `ngxp-install` before trying to do `start.android` and looking in the `nativescript node_modules` folder I can see the modules are there so I'm not sure why its not finding them.

**Comment by caraclarke** [comment]
I tried cloning a new version of the project and running `ngxp-install` and then `start.android` and got the same error

**Comment by caraclarke** [comment]
Fixed the issue by removing the `^` and locking `nativescript-theme-core` at `0.2.1`

`"nativescript-theme-core": "0.2.1"` in my `package.json` in the `nativescript` folder

**Comment by NathanWalker** [comment]
@caraclarke Once this PR https://github.com/shripalsoni04/nativescript-angular-web-starter/pull/2 is merged, `nativescript-theme-core` `0.2.2` as well as future updates to the core theme will work properly. We recently simplified the import paths for the theme 👍
